language: node_js
dist: trusty
sudo: required
node_js: "8"
script: npm test
cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-conversation-duo-dev
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
  - B_DOMAIN=ng.bluemix.net
  - secure: DYA04CYUyzD86/Obo/g3jEqn4rovvUOTFqwq4L3MqI2lKN4d7txJOSg6scHH9YmfOHZ7tQyJ+wKpGN/2iuhOxIZfITyBc213d+pic4GQ+M/2OgdO05s0nYlP4tkYBGP4byoJ+HSnrRk8A9wKx9OdAGRC0mu/rHq7udBhLn9FLhodVH8jAjcg4xyvyUnw819ioDgVkxNIYZFS36ErX0IlRX9KrxLWVNWmZ7j6dktxwcyNcM0t7PL0Z41vUwFRRDsPo8CefgY0z9/VfWVy1G4iYYF4qz1yRGXyrNJuV3aCfdNZOffcU6nQC9/unF4ghe0Fi/LAwbnOd4/xR1XS9yExR+uEEUO4bCTI/7SaG9FivkxEdSiC1SxiGm2/qgT7PI254o1+1hiL4IQQ4Jxp98gYUfpHTxtBbjh6bBbB1eCXkoi88ye5673pePv4xNlN9S5+trMrvDqv71NL4OM0jETQl9dsirz9ed/mURQzqYI2UJsHuIOqw/YIEr5bgo/tiihVe1yIap83547ibBtyewd7t7cZOgwXQzbtTsg+1cBtqxPtLSAVsKmkEh75f5J3zSr+CQT4TP1+5C6pMqhreolzFzvkrvqT62+PdAv9hhv7Dd3VUdfNWHCpPXsHv1dtgYIq7w60SEBzn2uuPDH4Rqj0Ke63FGSMeQ/JqOodbRSAPRQ=
  - secure: Z0WXbxW4fu2URhPZBJKN2J5IVs7fnonBkrOfFBy3jr2CukQjRUSyUc4A+IjRjofi77a3JTeuEZOZr8rE+VNHkRCsvkBzgP20v1GQHjgalKmJgk2++7BQ0ufnS0ky0JKWdlvpMuEyMzlfJz6kGrR6M91G9Rxb140tzNvRpgwxUPGYLo3C8eq4PM/Rlfd1KeGc4m+YlesViY+aeYBh7H4qWN02kQtz3sFrylhexeUOpY3Ah8dI9BApp7cIeg5ysY/sS0mNoDDJnJraNYE6eTSmGulYKkpVKKw2nRf9vnGGS+TDv9oaecK5SmakEgHjRClbKJ9l5wgtplfy4joib0U7owKUCEXmS/BRv61UlivBywxt9ix6aeTnwe6gnAOT1jLo+voRYJWeRtfyDoO7t3Iblw0RdynLdEBu5PGYIiXJGUy4Fb+2oXue0kzi8oR/MxpGAzezPinXRzavbP0pu3Shp3/Mc+ftk78o76kVSojxa3hAnTqApMSAwY5L4wlZujQKbuK9Y7GFw0BvoS8OOSwYeCSqtY+JpKOPn4BmY7G27kF8OsYgAYa2TxH84scublQ0qCtsNYCDq0bezGfePkkW0s0p73qjkfvOH5NSfh+axx9ykpJChT2+EcNuJG2L+UgbPg7HiqfVG2ZfuDykGTQ5Ncv8WBoH9GzRTS0l6WPzzG0=
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_cdd14ff783eb_key -iv $encrypted_cdd14ff783eb_iv -in .env.enc -out ./.env -d || true'
before_deploy:
- npm install -g bx-blue-green
- npm run build
deploy:
- provider: script
  script: bx-blue-green-travis
  on:
    branch: master
    repo: Watson/watson-conversation-demo-redesign
  skip_cleanup: true
- provider: script
  script: BX_APP=watson-conversation-duo-test bx-blue-green-travis
  on:
    branch: dev
    repo: Watson/watson-conversation-demo-redesign
  skip_cleanup: true
