language: node_js
dist: trusty
sudo: required
node_js: 6
script: npm test
cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-conversation-demo-redesign
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
  - CONVERSATION_API_KEY="bogus key to let server spin up for offline tests"
before_install:
- openssl aes-256-cbc -K $encrypted_cca766a893ae_key -iv $encrypted_cca766a893ae_iv
  -in .env.enc -out .env -d
before_deploy: npm install -g https://github.com/andresfvilla/bx-blue-green
deploy:
  provider: script
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: Watson/watson-conversation-demo-redesign 
  skip_cleanup: true
