language: node_js
dist: trusty
sudo: required
node_js: 6
script: npm test
cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-conversation-demo-redesign
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
  - B_DOMAIN=ng.bluemix.net
before_install:

before_deploy: npm install -g https://github.com/andresfvilla/bx-blue-green
deploy:
  provider: script
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: Watson/watson-conversation-demo-redesign 
  skip_cleanup: true
