language: node_js
dist: trusty
sudo: required
node_js: 6
script: npm test
cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-conversation-duo-dev
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
  - B_DOMAIN=ng.bluemix.net
  - secure: DCE35hZpM8n8fP/u7Q4ffnr2bAf9tsz43Tamjj9NwaiB/MmlCNKiahD8wGxGCuYLggslrAi/o3MkeCSjWnTZUCVz9j/MsH+ZvT02MxwitTeE6LMfobD/aIBJu8y/2NMMJRev/xR/OeknECYt3dgV5mlPWAn9JG5A8mK7ea9T4iKf2G2A1z+xFYhE2JbzMd4DqpnHoKnDPyls8YXnKAUZ0sJBs/3dDDeDjvahhvZjQpAuuWkRR4k5tZGAivlJtaWtFPMDs9V9OMd1FVSEJZaTwHjlseuJrgLTGnXwoHDlZhQKeYbtkXIQBi2MILFFJi5aSeUmiov2q+weVoB8UJrnSx0hdQdRGpe0qLHsAxSVFsYFoMJD4fu1MW577kLvfn5OTm8JYwRp3a69XFwM62IqB0ebLSxJaqwkp0m+Qqhfr7ES3d+wYp5HocSvExZoweFTkT3XuN7tyCm6oeDVJ2EvS3bGuodjppnwOq+Er/iHRBp/17Lm7ySNzVcuooLjRWeetW5CmYA8hzzMY+t/d9mf6bH3RZf6tQZ86XXv4sBPlgF4vinWWRDonRm2OkA4+eFPdph9uWbGjUDgr1vt4qtKnKXM86aCx23lKAqmffiTmeVGvHs9SMWctF8WJoUPdgEccAZDpUfKl16PrwV0dzWHT6N3YEr0D3BIQOERB1wBsUo=
  - secure: xp3zzDKH1plf7oomd22zjT1TL9usGQSwf83eNMcI9OJdpS6imoPPce7xKcrB1Dst7JQa3pj3cvESF4zyWhftZxKpgzC/Q8j/TYSIBtp4e2khG6+e8dOe1OybcNNHydISJ9aOLGreSdsu3SuRNSUIINK0xoV/yAlJZ8LaaHm2ucPiMSuddPv1STW0tFBQiluMVkSBT20Y4lgC5AgVzOGhPgMPMYI2K4/LuWbyUWtrravdnyXDNODALPnp3SlqpNK00oyRcRX/Isv6N6FvakywhcvtcG+XsdspqENJWefOBIxmJNhpkgs1+UPy3wjM7D38TUNTaVwGjLrpmp9mBk/A2uwh58gnYCqSErxquGuGf8l3XUbQs5ySdH01B0MjmsKkTEpm/xirOM1DtdWLBm6/nx88JaP61hQbHJC9LDqfLWrEeuQRNZ4fr4Eq+X8Lii/D3pf49vAZ363hhKEJGpGHLm6gqfTX/JiDC22vSU1//GG/BUYZnAaHcnfsQskYYbKHlOEn3YYN/9qiqvsoFl3AFsYZtm+ERDlEii53vi30GFHFP7BN02x0Mng3wX0owNK9m+QLv6+BXxl/0DHaz8n4aAli8uJE3feOveWHp5laOZcPgqi0X5kbpO7no0b8a9I93DnWD3/u4hlQHP2dfDXh5pW4E3cdOEOdQho1Mu+7OC4=
before_install: 
before_deploy: npm install -g https://github.com/andresfvilla/bx-blue-green
deploy:
  - provider: script
    script:
    - bx-blue-green-travis
    on:
      branch: dev
      repo: Watson/watson-conversation-demo-redesign
    skip_cleanup: true
  - provider: script
    script:
      -bx-blue-green-travis
    on:
      branch: master
      repo: Watson/watson-conversation-demo-redesign
